"use client";

import {FormEvent,useState} from "react";
import {getSupabaseBrowserClient} from "@/lib/supabase-browser";

const articles=[
  ["Стратегия","Зачем бизнесу вообще нужен монтажёр","Социальные сети требуют регулярного видео: знакомство с продуктом, ответы на возражения, кейсы, инструкции, новости и повторное касание с аудиторией. Монтажёр превращает исходники команды в понятную систему контента, следит за темпом, звуком, субтитрами и единым стилем.\n\nПостоянный специалист сокращает путь от идеи до публикации, накапливает знание бренда и помогает тестировать несколько подач одной мысли. Оценивайте его вклад по скорости выпуска, соблюдению брифа, удержанию, целевым действиям и числу правок — просмотры сами по себе дают неполную картину."],
  ["Бриф","Как получить сравнимые работы","Дайте всем монтажёрам одинаковые исходники, цель, формат, длительность и критерии оценки. Так выбор основывается на результате, а не на разном понимании задачи.\n\nОтдельно обозначьте обязательные факты, запрещённые обещания, референсы только по конкретным признакам и одно главное действие зрителя. До старта назначьте человека, который собирает финальные правки от команды."],
  ["Метрики","Что смотреть кроме просмотров","Сравнивайте удержание первых секунд, досмотры, сохранения, переходы и целевое действие. Одна метрика редко объясняет результат целиком."],
  ["Команда","Как давать правки без хаоса","Соберите комментарии в один список: обязательные исправления, идеи для следующей версии и то, что уже работает. Назначьте одного человека, который подтверждает финал."],
  ["Контент","Когда масштабировать формат","Повторяйте формат после нескольких сильных результатов, сохраняя основу и меняя начало, пример или подачу. Один удачный ролик ещё не доказывает закономерность."],
  ["Подбор","Как выбрать постоянного монтажёра","Оцените соблюдение брифа, срок, качество коммуникации и реакцию на одну содержательную правку — не только красивый первый вариант."],
  ["Креаторы","Реклама за результат","Создайте понятную кампанию: продукт, допустимые тезисы, формат интеграции и награда в KIVRONIX Points за подтверждённые просмотры."]
];

const articleChapters=[
  ["Начните с результата","Сформулируйте одним предложением, какое действие зрителя должно измениться после публикации. Для знакомства с продуктом, ответа на возражение и продажи нужны разные сценарии, темп и призывы. Такая формулировка помогает монтажёру принимать решения, а команде — оценивать работу по общему критерию."],
  ["Передайте контекст, а не набор пожеланий","Добавьте в бриф аудиторию, площадку, обязательные факты, ограничения бренда и один-два референса с пояснением конкретного приёма. Фраза «сделать динамично» допускает десятки трактовок, а просьба показать результат в первые две секунды создаёт проверяемую задачу."],
  ["Разделите черновик и финал","Сначала согласуйте структуру, смысл и порядок кадров. Цвет, графику и точную работу со звуком доводите после подтверждения чернового монтажа. Это сокращает лишние циклы и защищает бюджет от переделки уже отполированной сцены."],
  ["Собирайте правки в одном месте","Назначьте одного ответственного, объединяющего комментарии команды. Каждая правка должна содержать таймкод, наблюдение и желаемый результат. Отделяйте обязательные изменения от идей для следующей версии: так монтажёр понимает приоритет, а история решений остаётся прозрачной."],
  ["Оценивайте серию, а не случайный всплеск","Сравнивайте несколько публикаций одного формата. Смотрите удержание первых секунд, досмотры, переходы и целевые действия вместе. Зафиксируйте, что изменилось между версиями, иначе сильный результат невозможно повторить, а слабый — правильно объяснить."],
  ["Завершайте работу договорённостью","Перед стартом запишите формат файлов, срок первой версии, число кругов правок и критерий готовности. После публикации проведите короткий разбор: что сработало, что проверить в следующий раз и какие материалы стоит снимать иначе. Так отдельный ролик превращается в накопленный процесс."],
];

type Message={id:string;content:string;createdAt:string;author:string};

export default function BusinessInsights(){
  const [open,setOpen]=useState(false),[openedArticle,setOpenedArticle]=useState<number|null>(null),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(false);
  async function headers(){const {data:{session}}=await getSupabaseBrowserClient().auth.getSession();return session?.access_token?{Authorization:"Bearer "+session.access_token}:{} as Record<string,string>}
  async function load(){setLoading(true);setNotice("");const r=await fetch("/api/community/business-discussion",{headers:await headers(),cache:"no-store"});const d=await r.json();setLoading(false);if(!r.ok){setNotice(d.error||"Не удалось открыть обсуждение.");return}setMessages(d.messages||[]);setOpen(true)}
  async function send(e:FormEvent){e.preventDefault();if(!draft.trim())return;setLoading(true);const r=await fetch("/api/community/business-discussion",{method:"POST",headers:{...await headers(),"Content-Type":"application/json"},body:JSON.stringify({content:draft})});const d=await r.json();setLoading(false);if(!r.ok){setNotice(d.error||"Не удалось отправить сообщение.");return}setMessages(d.messages||[]);setDraft("")}
  return <div className="insights-hub">
    <section className="insights-topic business-topic"><div><div className="eyebrow">ЗАКРЫТЫЙ КЛУБ КОМПАНИЙ</div><h2>Как находить сильных монтажёров и удерживать их в команде?</h2><p>Обсуждение доступно только владельцам бизнес-аккаунтов KIVRONIX. Сообщения монтажёров сюда не попадают.</p></div><button className="btn btn-lime" onClick={()=>void load()} disabled={loading}>{loading?"Открываем…":"Открыть обсуждение компаний"}</button></section>
    {notice?<div className="auth-msg">{notice}</div>:null}
    {open?<section className="confidential-discussion"><header><div><div className="eyebrow">ТОЛЬКО КОМПАНИИ</div><h3>Работа с видео-командой</h3></div><button className="btn btn-ghost" onClick={()=>setOpen(false)}>Закрыть</button></header><div className="discussion-privacy"><b>Конфиденциально внутри KIVRONIX</b><span>Доступ проверяется по роли аккаунта. Публичного просмотра нет.</span></div><div className="discussion-feed">{messages.length?messages.map(m=><article key={m.id}><b>{m.author}</b><p>{m.content}</p><small>{new Date(m.createdAt).toLocaleString("ru-RU")}</small></article>):<div className="discussion-empty"><b>Начните профессиональное обсуждение</b><span>Поделитесь задачей найма, брифа или организации контента.</span></div>}</div><form className="discussion-form" onSubmit={send}><textarea required maxLength={1400} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Сообщение другим компаниям без личных данных…"/><button className="btn btn-dark" disabled={loading}>Отправить</button></form></section>:null}
    <div className="insights-grid">{articles.map(([tag,title,text],index)=><article className={"insight-card "+(openedArticle===index?"article-paper":"")} key={title}><span>{tag}</span><h3>{title}</h3><p>{text.split("\n\n")[0]}</p>{openedArticle===index?<div className="insight-body">{text.split("\n\n").slice(1).map(paragraph=><p key={paragraph}>{paragraph}</p>)}{articleChapters.map(([chapter,copy])=><section className="article-chapter" key={chapter}><h4>{chapter}</h4><p>{copy}</p></section>)}<section className="article-summary"><h4>Проверка перед запуском</h4><ul><li>Цель ролика выражена одним предложением</li><li>Аудитория и площадка указаны в брифе</li><li>Срок и число правок согласованы</li><li>Комментарии собраны с таймкодами</li><li>Метрики выбраны заранее</li></ul></section></div>:null}<button className="insight-toggle" type="button" onClick={()=>setOpenedArticle(openedArticle===index?null:index)}>{openedArticle===index?"Свернуть":"Открыть подробную статью →"}</button></article>)}</div>
  </div>;
}
