"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "@/lib/supabase-browser";
import ProfileAvatar from "@/components/profile-avatar";

type Editor={id:string;display_name?:string;username?:string;avatar_url?:string;levelLabel:string;xp:number;ai_score?:number|null;skills?:string[];portfolioCount:number;reviewCount:number;rating:number|null};

export default function EditorDirectory({onOpenMessages}:{onOpenMessages:()=>void}){
  const [editors,setEditors]=useState<Editor[]>([]),[query,setQuery]=useState(""),[level,setLevel]=useState("all"),[message,setMessage]=useState(""),[busy,setBusy]=useState(""),[reviewing,setReviewing]=useState<string|null>(null),[rating,setRating]=useState(5),[comment,setComment]=useState("");
  useEffect(()=>{void load()},[]);
  async function token(){const {data:{session}}=await getSupabaseBrowserClient().auth.getSession();return session?.access_token||""}
  async function load(){const access=await token();if(!access)return;const response=await fetch("/api/editor-directory",{headers:{Authorization:"Bearer "+access},cache:"no-store"});const data=await response.json();if(response.ok)setEditors(data.editors||[]);else setMessage(data.error||"Не удалось загрузить каталог.")}
  const visible=useMemo(()=>editors.filter(editor=>(level==="all"||editor.levelLabel===level)&&(`${editor.display_name||""} ${editor.username||""} ${(editor.skills||[]).join(" ")}`).toLowerCase().includes(query.toLowerCase())),[editors,query,level]);
  async function openChat(editorId:string){setBusy(editorId);setMessage("");const access=await token();const response=await fetch("/api/private-chats",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+access},body:JSON.stringify({action:"open_editor",editorId})});const data=await response.json();setBusy("");if(!response.ok){setMessage(data.error||"Не удалось открыть чат.");return}try{sessionStorage.setItem("kivronix_open_conversation",data.conversationId)}catch{}onOpenMessages()}
  async function sendReview(editorId:string){const access=await token();const response=await fetch("/api/editor-directory",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+access},body:JSON.stringify({editorId,rating,comment})});const data=await response.json();if(!response.ok){setMessage(data.error||"Отзыв не сохранён.");return}setMessage("Отзыв прошёл автоматическую модерацию и опубликован.");setReviewing(null);setComment("");await load()}
  return <div className="editor-directory">
    <section className="directory-intro"><div><div className="eyebrow">ПОЛНЫЙ КАТАЛОГ МОНТАЖЁРОВ</div><h2>Все монтажёры платформы в одном списке</h2><p>Блогеры и компании видят полный каталог без скрытой подборки: сравнивайте уровень, работы, ИИ‑оценку и реальные отзывы, затем открывайте закрытый рабочий чат.</p></div><div className="directory-count"><strong>{editors.length}</strong><span>всего профилей</span></div></section>
    <div className="directory-filters"><input type="search" placeholder="Имя, навык или @username" value={query} onChange={event=>setQuery(event.target.value)}/><div className="level-filter-pills"><button className={level==="all"?"active":""} onClick={()=>setLevel("all")}>Все уровни</button>{[...new Set(editors.map(item=>item.levelLabel))].map(item=><button className={level===item?"active":""} onClick={()=>setLevel(item)} key={item}>{item}</button>)}</div></div>
    <div className="editor-directory-grid">{visible.map(editor=><article className="editor-card" key={editor.id}><header><ProfileAvatar src={editor.avatar_url} name={editor.display_name||"Монтажёр"}/><div><h3>{editor.display_name||"Монтажёр"}</h3><span>@{editor.username||"editor"}</span></div><b>{editor.levelLabel}</b></header><div className="editor-metrics"><span><strong>{editor.rating?.toFixed(1)||"—"}</strong> рейтинг</span><span><strong>{editor.portfolioCount}</strong> видео</span><span><strong>{editor.ai_score||"—"}</strong> AI‑балл</span></div><div className="chip-row">{(editor.skills||[]).slice(0,4).map(skill=><span className="tag" key={skill}>{skill}</span>)}</div><div className="editor-actions">{editor.username?<Link className="btn btn-ghost" href={`/u/${editor.username}`} target="_blank">Портфолио</Link>:<button className="btn btn-ghost" disabled>Портфолио пусто</button>}<button className="btn btn-dark" disabled={busy===editor.id} onClick={()=>void openChat(editor.id)}>{busy===editor.id?"Открываем…":"Начать диалог"}</button></div><button className="review-link" type="button" onClick={()=>setReviewing(reviewing===editor.id?null:editor.id)}>Оставить отзыв после работы · {editor.reviewCount}</button>{reviewing===editor.id?<div className="review-form-inline"><label>Оценка<select value={rating} onChange={event=>setRating(Number(event.target.value))}>{[5,4,3,2,1].map(value=><option key={value} value={value}>{value} из 5</option>)}</select></label><textarea maxLength={800} minLength={10} value={comment} onChange={event=>setComment(event.target.value)} placeholder="Конкретно и уважительно: сроки, качество, коммуникация…"/><button className="btn btn-lime" disabled={comment.trim().length<10} onClick={()=>void sendReview(editor.id)}>Отправить на модерацию</button></div>:null}</article>)}</div>
    {!visible.length?<div className="auth-msg">Под этот фильтр пока нет профилей.</div>:null}{message?<div className="auth-msg">{message}</div>:null}
  </div>;
}
