"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {getFreshAccessToken} from "@/lib/supabase-browser";
import ProfileAvatar from "@/components/profile-avatar";
type Partner={id:string;displayName:string;username?:string;avatarUrl?:string;kind:"creator"|"business";description:string;skills:string[]};
export default function PartnerDirectory(){
 const [items,setItems]=useState<Partner[]>([]),[kind,setKind]=useState("all"),[query,setQuery]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{void(async()=>{const token=await getFreshAccessToken();const response=await fetch("/api/partner-directory",{headers:{Authorization:"Bearer "+token},cache:"no-store"});const data=await response.json();if(response.ok)setItems(data.partners||[]);else setMessage(data.error)})()},[]);
 const visible=useMemo(()=>items.filter(item=>(kind==="all"||item.kind===kind)&&`${item.displayName} ${item.username||""} ${item.description}`.toLowerCase().includes(query.toLowerCase())),[items,kind,query]);
 return <div className="partner-directory"><section className="directory-intro"><div><div className="eyebrow">КАТАЛОГ ЗАКАЗЧИКОВ</div><h2>Блогеры и компании, которым нужен монтаж</h2><p>Изучи профиль, задачи и стиль партнёра. Рабочие договорённости, файлы и оплата остаются внутри KIVRONIX.</p></div><div className="directory-count"><strong>{items.length}</strong><span>профилей</span></div></section><div className="directory-filters"><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Название, ник или направление"/><div className="level-filter-pills"><button className={kind==="all"?"active":""} onClick={()=>setKind("all")}>Все</button><button className={kind==="creator"?"active":""} onClick={()=>setKind("creator")}>Блогеры</button><button className={kind==="business"?"active":""} onClick={()=>setKind("business")}>Компании</button></div></div><div className="partner-grid">{visible.map(item=><article className="partner-card" key={item.id}><header><ProfileAvatar src={item.avatarUrl} name={item.displayName}/><div><h3>{item.displayName}</h3><span>{item.kind==="creator"?"Блогер":"Компания"}{item.username?` · @${item.username}`:""}</span></div></header><p>{item.description}</p><div className="chip-row">{item.skills.slice(0,4).map(skill=><span className="tag" key={skill}>{skill}</span>)}</div>{item.username?<Link className="btn btn-dark" href={`/u/${item.username}`}>Открыть профиль</Link>:<span className="muted">Публичный профиль заполняется</span>}</article>)}</div>{!visible.length?<div className="auth-msg">Под выбранный фильтр профилей пока нет.</div>:null}{message?<div className="auth-msg">{message}</div>:null}</div>
}
