"use client";
import {useEffect,useState} from "react";
import {getFreshAccessToken} from "@/lib/supabase-browser";

export default function PlatformReviewForm(){
  const [existing,setExisting]=useState<any>(undefined),[text,setText]=useState(""),[rating,setRating]=useState(5),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{void(async()=>{const token=await getFreshAccessToken();if(!token)return;const response=await fetch("/api/platform-reviews",{headers:{Authorization:"Bearer "+token},cache:"no-store"});if(response.ok)setExisting((await response.json()).review)})()},[]);
  async function submit(){setBusy(true);setMessage("");try{const token=await getFreshAccessToken();const response=await fetch("/api/platform-reviews",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({text,rating})});const data=await response.json();if(!response.ok)throw new Error(data.error);setExisting({status:"pending"});setMessage("Спасибо! Отзыв отправлен на модерацию. После публикации начислим 10 бонусных Points.")}catch(error){setMessage(error instanceof Error?error.message:"Не удалось отправить отзыв.")}finally{setBusy(false)}}
  return <section className="platform-review-card"><div><div className="eyebrow">ПОМОГИ УЛУЧШИТЬ KIVRONIX</div><h3>Расскажи о своём опыте</h3><p>Один честный отзыв можно отправить один раз. После модерации он появится на главной, а в профиль начислятся 10 бонусных Points.</p></div>{existing!==undefined?(existing?<div className="review-status"><b>{existing.status==="approved"?"Отзыв опубликован":"Отзыв на модерации"}</b><span>{existing.reward_awarded?"10 бонусных Points начислены":"Мы сообщим результат в кабинете"}</span></div>:<div className="review-compose"><select value={rating} onChange={event=>setRating(Number(event.target.value))}>{[5,4,3,2,1].map(value=><option value={value} key={value}>{value} из 5</option>)}</select><textarea minLength={40} maxLength={1400} value={text} onChange={event=>setText(event.target.value)} placeholder="Что было полезно? Что стоит улучшить?"/><button className="btn btn-lime" disabled={busy||text.trim().length<40} onClick={()=>void submit()}>{busy?"Отправляем…":"Отправить на модерацию"}</button></div>):<span>Проверяем статус…</span>}{message?<div className="auth-msg">{message}</div>:null}</section>
}
