"use client";
import {useEffect,useState} from "react";
import {getSupabaseBrowserClient} from "@/lib/supabase-browser";
export default function WorkWallet(){
 const [wallet,setWallet]=useState({available:0,reserved:0,topupFeePercent:0,workFeePercent:0});const [points,setPoints]=useState("1000");const [message,setMessage]=useState("");const [loading,setLoading]=useState(false);const [open,setOpen]=useState(false);
 async function headers():Promise<Record<string,string>>{const {data}=await getSupabaseBrowserClient().auth.getSession();return data.session?{Authorization:"Bearer "+data.session.access_token}:{};}
 async function load(){const r=await fetch("/api/points",{headers:await headers(),cache:"no-store"});if(r.ok)setWallet(await r.json());}
 useEffect(()=>{void load()},[]);
 async function topup(){setLoading(true);setMessage("");const r=await fetch("/api/points",{method:"POST",headers:{...(await headers()),"Content-Type":"application/json"},body:JSON.stringify({points:Number(points)})});const data=await r.json().catch(()=>({}));setLoading(false);if(r.ok&&data.url)window.location.assign(data.url);else setMessage(data.error||"Не удалось начать пополнение.");}
 const pointCount=Math.max(0,Math.floor(Number(points)||0));const totalRub=Math.round(pointCount*(1+wallet.topupFeePercent/100)*100)/100;
 return <section className="card wallet-card"><div className="wallet-card-head"><div><div className="eyebrow">БАЛАНС ДЛЯ РАБОТ</div><h3>{wallet.available.toLocaleString("ru-RU")} KP доступно</h3></div><button className="btn btn-dark" onClick={()=>setOpen(value=>!value)}>{open?"Закрыть":"Пополнить баланс"}</button></div><p className="muted">В резерве: {wallet.reserved.toLocaleString("ru-RU")} KP. 1 KIVRONIX Point = 1 ₽, а монтажёр получает 100% указанной в задании суммы.</p>{open?<div className="wallet-topup-panel"><div><b>Сколько начислить?</b><span>Без комиссии за пополнение и автоматических списаний</span></div><div className="wallet-presets">{[500,1000,3000,5000].map(value=><button type="button" className={pointCount===value?"active":""} onClick={()=>setPoints(String(value))} key={value}>{value.toLocaleString("ru-RU")} KP</button>)}</div><div className="split-fields"><input aria-label="Количество KIVRONIX Points" type="number" min="100" max="1000000" value={points} onChange={e=>setPoints(e.target.value)}/><button className="btn btn-lime" onClick={topup} disabled={loading}>{loading?"Открываем оплату…":"Оплатить "+totalRub.toLocaleString("ru-RU")+" ₽"}</button></div><p className="muted">Зачислим {pointCount.toLocaleString("ru-RU")} KP · к оплате {totalRub.toLocaleString("ru-RU")} ₽.</p></div>:null}{message&&<div className="auth-msg">{message}</div>}</section>;
}
