import type {Lesson} from "@/lib/curriculum";

export type EditingGlossaryEntry={
  english:string;
  russian:string;
  explanation:string;
  example:string;
  programs:string;
  commonMistake:string;
  keywords:string[];
};

export const editingGlossary:EditingGlossaryEntry[]=[
  {english:"Timeline",russian:"Лента монтажа",explanation:"Шкала времени, где по порядку лежат видео, звук, музыка и текст.",example:"Поставь первый клип в начало ленты монтажа.",programs:"CapCut, Adobe Premiere Pro, DaVinci Resolve, Final Cut Pro",commonMistake:"Перемещать клип на другую дорожку и случайно закрывать им нужный материал.",keywords:["лента монтажа","таймлайн","timeline","дорожк"]},
  {english:"Import",russian:"Импорт",explanation:"Добавление исходных видео, фотографий и звука в проект. Файлы при этом не превращаются в готовый ролик.",example:"Импортируй три исходных клипа перед началом монтажа.",programs:"Все видеоредакторы",commonMistake:"Удалять исходник с компьютера после импорта, из-за чего программа перестаёт его находить.",keywords:["импорт","исходник","добавь файл","медиатек"]},
  {english:"Export",russian:"Экспорт",explanation:"Создание готового видеофайла из проекта, который можно открыть и опубликовать.",example:"Экспортируй ролик в MP4 и посмотри его целиком.",programs:"Все видеоредакторы",commonMistake:"Считать сохранение проекта экспортом готового видео.",keywords:["экспорт","готовый файл","сохранение готового видео"]},
  {english:"Render",russian:"Просчёт видео",explanation:"Создание кадров с применёнными эффектами. Он может происходить во время просмотра или экспорта.",example:"После сложного эффекта редактору нужно время на просчёт.",programs:"Adobe Premiere Pro, DaVinci Resolve, Final Cut Pro",commonMistake:"Закрывать программу во время просчёта или ждать, что он исправит ошибки монтажа.",keywords:["рендер","render","просчёт"]},
  {english:"Frame rate / FPS",russian:"Частота кадров",explanation:"Количество отдельных кадров в одной секунде видео.",example:"Если исходник снят в 30 FPS, проект обычно настраивают на 30 FPS.",programs:"Все видеоредакторы",commonMistake:"Менять FPS без причины и получать рывки движения.",keywords:["fps","кадр в секунду","частота кадров"]},
  {english:"Bitrate",russian:"Битрейт",explanation:"Количество данных для одной секунды видео. Более высокий битрейт обычно даёт лучшее качество и больший файл.",example:"При слишком низком битрейте мелкий текст может рассыпаться на квадраты.",programs:"Окна экспорта всех видеоредакторов",commonMistake:"Ставить максимальное значение без учёта площадки и размера файла.",keywords:["битрейт","bitrate"]},
  {english:"Codec",russian:"Кодек",explanation:"Способ сжатия и хранения изображения или звука внутри видеофайла.",example:"H.264 часто используют для публикации MP4 в социальных сетях.",programs:"Окна экспорта всех видеоредакторов",commonMistake:"Путать кодек с расширением файла: MP4 — контейнер, H.264 — кодек.",keywords:["кодек","h.264","h.265","hevc"]},
  {english:"Project",russian:"Проект",explanation:"Рабочий файл редактора с монтажом, настройками и ссылками на исходники.",example:"Сохрани проект отдельно от готового MP4.",programs:"Все видеоредакторы",commonMistake:"Отправлять клиенту файл проекта вместо готового видео.",keywords:["проект","project"]},
  {english:"Sequence",russian:"Монтажная последовательность",explanation:"Настроенная рабочая лента с размером кадра, частотой кадров и расположенными клипами.",example:"Создай вертикальную последовательность 1080 × 1920.",programs:"Adobe Premiere Pro",commonMistake:"Начинать монтаж в последовательности с неправильным размером кадра.",keywords:["sequence","последовательност","1080 × 1920"]},
  {english:"Media",russian:"Медиафайлы",explanation:"Все исходные видео, фотографии, музыка, речь и графика проекта.",example:"Собери медиафайлы по папкам до начала монтажа.",programs:"Все видеоредакторы",commonMistake:"Хранить файлы без понятных названий и терять нужный дубль.",keywords:["медиа","файлы","исходные видео"]},
  {english:"Keyframe",russian:"Ключевой кадр",explanation:"Точка, где задаётся конкретное значение параметра; между точками программа создаёт плавное изменение.",example:"Поставь ключевые кадры масштаба в начале и конце приближения.",programs:"CapCut, Adobe Premiere Pro, DaVinci Resolve, Final Cut Pro",commonMistake:"Ставить только одну точку и ждать движения.",keywords:["ключев","keyframe","анимац"]},
  {english:"Mask",russian:"Маска",explanation:"Область, которая показывает или скрывает выбранную часть изображения.",example:"Маской можно размыть лицо, не затрагивая остальной кадр.",programs:"CapCut, Adobe Premiere Pro, DaVinci Resolve, Final Cut Pro",commonMistake:"Забывать двигать маску за объектом.",keywords:["маск","mask"]},
  {english:"Overlay",russian:"Наложение",explanation:"Дополнительное видео, изображение или текст поверх основного кадра.",example:"Размести снимок экрана на дорожке над речью героя.",programs:"CapCut, Adobe Premiere Pro, DaVinci Resolve, Final Cut Pro",commonMistake:"Перекрывать наложением лицо, субтитры или важное действие.",keywords:["наложен","overlay","поверх"]},
  {english:"B-roll",russian:"Дополнительные кадры",explanation:"Кадры поверх основной речи, которые показывают предмет, действие или пример из сказанного.",example:"На словах о приложении покажи запись его экрана.",programs:"Все видеоредакторы",commonMistake:"Добавлять случайный красивый кадр, не связанный с фразой.",keywords:["b-roll","дополнительные кадры"]},
  {english:"Proxy",russian:"Облегчённая копия",explanation:"Временная копия исходника меньшего размера для плавной работы на слабом компьютере.",example:"Создай прокси для тяжёлого 4K-видео, а экспорт выполни из оригинала.",programs:"Adobe Premiere Pro, DaVinci Resolve, Final Cut Pro",commonMistake:"Экспортировать облегчённую копию вместо оригинала.",keywords:["прокси","proxy","4k"]},
  {english:"Preset",russian:"Набор настроек",explanation:"Сохранённые заранее параметры эффекта или экспорта.",example:"Используй проверенный набор настроек для вертикального MP4.",programs:"Все видеоредакторы",commonMistake:"Применять один набор к любому материалу без проверки результата.",keywords:["пресет","preset","набор настроек"]},
  {english:"Transition",russian:"Переход",explanation:"Способ смены одного клипа другим. Обычная склейка тоже является переходом.",example:"Используй короткое затемнение, когда меняется время или место.",programs:"Все видеоредакторы",commonMistake:"Ставить заметный эффект между каждым клипом.",keywords:["переход","transition"]},
  {english:"Color correction",russian:"Цветокоррекция",explanation:"Исправление яркости, баланса белого и различий между кадрами.",example:"Сначала выровняй слишком тёмный кадр, затем добавляй стиль.",programs:"CapCut, Adobe Premiere Pro, DaVinci Resolve, Final Cut Pro",commonMistake:"Начинать с сильного фильтра, не исправив экспозицию.",keywords:["цветокоррек","баланс белого","экспозиц"]},
  {english:"Color grading",russian:"Цветовой стиль",explanation:"Осознанное художественное оформление цвета после технического исправления кадров.",example:"Сделай тёплый цветовой стиль для уютной истории.",programs:"Adobe Premiere Pro, DaVinci Resolve, Final Cut Pro, CapCut",commonMistake:"Путать стиль с исправлением технических проблем изображения.",keywords:["цветовой стиль","color grading","грейдинг"]},
  {english:"Crop",russian:"Кадрирование",explanation:"Обрезка краёв изображения без изменения длительности клипа.",example:"Убери лишний предмет у правого края кадра.",programs:"Все видеоредакторы",commonMistake:"Обрезать важный объект или оставить слишком мало пространства вокруг лица.",keywords:["кадрирован","crop","обрезк"]},
  {english:"Transform",russian:"Трансформация",explanation:"Настройки положения, масштаба и поворота изображения.",example:"Увеличь масштаб и перемести лицо ближе к центру вертикального кадра.",programs:"CapCut, Adobe Premiere Pro, DaVinci Resolve, Final Cut Pro",commonMistake:"Слишком сильно увеличивать изображение и терять чёткость.",keywords:["transform","трансформац","масштаб","положен"]},
  {english:"Inspector",russian:"Инспектор",explanation:"Панель параметров выбранного клипа: положение, масштаб, звук, эффекты и другие свойства.",example:"Выбери клип и открой Inspector / Инспектор, чтобы изменить масштаб.",programs:"DaVinci Resolve, Final Cut Pro",commonMistake:"Менять параметры, не выбрав нужный клип.",keywords:["inspector","инспектор"]},
  {english:"Media Pool",russian:"Медиатека",explanation:"Панель с исходными файлами текущего проекта.",example:"Создай в Media Pool / Медиатеке папки «Видео», «Звук» и «Графика».",programs:"DaVinci Resolve",commonMistake:"Путать медиатеку с лентой монтажа.",keywords:["media pool","медиатек"]},
  {english:"Source Monitor",russian:"Окно исходника",explanation:"Окно предварительного просмотра отдельного исходного клипа до добавления в монтаж.",example:"Выбери нужный фрагмент в окне исходника.",programs:"Adobe Premiere Pro",commonMistake:"Принимать окно исходника за готовый ролик.",keywords:["source monitor","окно исходника"]},
  {english:"Program Monitor",russian:"Окно результата",explanation:"Окно, где виден кадр собранной последовательности в текущий момент.",example:"Проверь субтитры в окне результата.",programs:"Adobe Premiere Pro",commonMistake:"Смотреть только отдельный исходник и не проверять общий монтаж.",keywords:["program monitor","окно результата","окно просмотра"]},
  {english:"Reference",russian:"Референс",explanation:"Пример, который помогает согласовать настроение, темп или приём, но не требует точного копирования.",example:"Покажи два референса темпа перед началом работы.",programs:"Работа с клиентом и все видеоредакторы",commonMistake:"Копировать чужую работу целиком вместо разбора конкретного приёма.",keywords:["референс","reference"]},
  {english:"Technical brief",russian:"Техническое задание",explanation:"Письменное описание результата, формата, срока, материалов и критериев готовности.",example:"Зафиксируй длительность, площадку и обязательные элементы до монтажа.",programs:"Работа с клиентом",commonMistake:"Начинать работу по разрозненным сообщениям без единого итога.",keywords:["техническое задание","тз","бриф","brief"]},
  {english:"Draft",russian:"Черновик",explanation:"Промежуточная версия для проверки структуры и основных решений.",example:"Сначала отправь черновик с водяным знаком на согласование.",programs:"Работа с клиентом",commonMistake:"Выдавать черновик за полностью готовый результат.",keywords:["черновик","draft"]},
  {english:"Revision",russian:"Правка",explanation:"Конкретное изменение согласованного черновика по понятному замечанию.",example:"Правка: на 00:12 увеличить субтитр и оставить его на экране ещё секунду.",programs:"Работа с клиентом",commonMistake:"Принимать фразу «сделай лучше» без уточнения ожидаемого результата.",keywords:["правк","revision"]},
  {english:"Portfolio",russian:"Портфолио",explanation:"Подборка лучших работ, по которой заказчик понимает уровень и специализацию автора.",example:"Поставь первой работу, похожую на желаемые заказы.",programs:"Профиль KIVRONIX",commonMistake:"Добавлять много случайных работ вместо нескольких сильных и разных примеров.",keywords:["портфолио","portfolio","кейс"]},
];

export function glossaryForLesson(lesson:Lesson){
  const text=[lesson.title,lesson.summary,lesson.simple,lesson.example,lesson.assignment,...lesson.steps,...lesson.checklist,...lesson.mistakes,...(lesson.words||[]).flatMap(item=>[item.term,item.meaning])].join(" ").toLocaleLowerCase("ru-RU");
  const matches=editingGlossary.filter(entry=>entry.keywords.some(keyword=>text.includes(keyword.toLocaleLowerCase("ru-RU"))));
  return (matches.length?matches:lesson.slug==="editor-words"?editingGlossary.slice(0,8):[]).slice(0,8);
}
